### Q.11 :
**floor**

The tool floor returns the floor of the input element-wise.
The floor of x is the largest integer i where i <= x.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

**ceil**

The tool ceil returns the ceiling of the input element-wise.
The ceiling of  is the smallest integer  where .

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

**rint**

The rint tool rounds to the nearest integer of input element-wise.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

**Task**

You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

**Note**

In order to get the correct output format, add the line 
numpy.set_printoptions(legacy = '1.13') below the numpy import.

**Input Format**

A single line of input containing the space separated elements of array A.

**Output Format**

On the first line, print the floor of A.
On the second line, print the ceil of A.
On the third line, print the rint of A.

### Answer :

In [7]:
import numpy

numpy.set_printoptions(legacy='1.13')

A = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

print(numpy.floor(A))

print(numpy.ceil(A))

print(numpy.rint(A))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Q.12 :
**sum**

The sum tool returns the sum of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10
By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.

**prod**

The prod tool returns the product of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
By default, the axis value is None. Therefore, it performs the product over all the dimensions of the input array.

**Task**

You are given a 2-D array with dimensions NxM.
Your task is to perform the sum tool over axis 0 and then find the prod of that result.

**Input Format**

The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

Compute the sum along axis 0. Then, print the product of that sum.

### Answer :

In [41]:
import numpy

array = numpy.array([ [1, 2], [3, 4] ])

sum_values = numpy.sum(array, axis=0)

prod_value = numpy.prod(sum_values)

print(prod_value)


24


### Q.13 :
**min**

The tool min returns the minimum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]
print numpy.min(my_array, axis = None)      #Output : 0
print numpy.min(my_array)                   #Output : 0
By default, the axis value is None. Therefore, it finds the minimum over all the dimensions of the input array.

**max**

The tool max returns the maximum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]
print numpy.max(my_array, axis = None)      #Output : 7
print numpy.max(my_array)                   #Output : 7
By default, the axis value is None. Therefore, it finds the maximum over all the dimensions of the input array.

**Task**

You are given a 2-D array with dimensions NxM.
Your task is to perform the min function over axis 1 and then find the max of that.

**Input Format**

The first line of input contains the space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

Compute the min along axis 1 and then print the max of that result.

### Answer :

In [40]:
import numpy

array = numpy.array([[2,5], [3,7], [1,3], [4,0]])

min_values = numpy.min(array, axis=1)

max_value = numpy.max(min_values)

print(max_value)

3


### Q.14 :
**mean**

The mean tool computes the arithmetic mean along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.mean(my_array, axis = 0)        #Output : [ 2.  3.]
print numpy.mean(my_array, axis = 1)        #Output : [ 1.5  3.5]
print numpy.mean(my_array, axis = None)     #Output : 2.5
print numpy.mean(my_array)                  #Output : 2.5
By default, the axis is None. Therefore, it computes the mean of the flattened array.

**var**

The var tool computes the arithmetic variance along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.var(my_array, axis = 0)         #Output : [ 1.  1.]
print numpy.var(my_array, axis = 1)         #Output : [ 0.25  0.25]
print numpy.var(my_array, axis = None)      #Output : 1.25
print numpy.var(my_array)                   #Output : 1.25
By default, the axis is None. Therefore, it computes the variance of the flattened array.

**std**

The std tool computes the arithmetic standard deviation along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.std(my_array, axis = 0)         #Output : [ 1.  1.]
print numpy.std(my_array, axis = 1)         #Output : [ 0.5  0.5]
print numpy.std(my_array, axis = None)      #Output : 1.11803398875
print numpy.std(my_array)                   #Output : 1.11803398875
By default, the axis is None. Therefore, it computes the standard deviation of the flattened array.

**Task**

You are given a 2-D array of size X.
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis None

**Input Format**

The first line contains the space separated values of N and M.
The next N lines contains M space separated integers.

**Output Format**

First, print the mean.
Second, print the var.
Third, print the std.

### Answer :

In [39]:
import numpy

array = numpy.array([ [1, 2], [3, 4] ])

mean_value = numpy.mean(array, axis=1)

var_value = numpy.var(array, axis=0)

std_value = numpy.std(array, axis=None)

print(mean_value)
print(var_value)
print(round(std_value, 11))

[1.5 3.5]
[1. 1.]
1.11803398875


### Q.15 :
**dot**

The dot tool returns the dot product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.dot(A, B)       #Output : 11

**cross**

The cross tool returns the cross product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print numpy.cross(A, B)     #Output : -2

**Task**

You are given two arrays A and B. Both have dimensions of NxN.
Your task is to compute their matrix product.

**Input Format**

The first line contains the integer N.
The next N lines contains N space separated integers of array A.
The following N lines contains N space separated integers of array B.

**Output Format**

Print the matrix multiplication of A and B.

### Answer :

In [75]:
import numpy

N = 2

A = numpy.array([[1,2], [3,4]])

B = numpy.array([[5,6], [7,8]])

matrix_product = numpy.dot(A, B)
 
print(matrix_product)

[[19 22]
 [43 50]]
